version: "3"
services:
  torch_local:
    container_name: torch_local
    image: torch_local:1.0
    build:
      context: ./docker
      dockerfile: ./Dockerfile
    restart: always
    tty: true
    ports:
      - "8888:8888"
      - "6006:6006"
    volumes:
      - .:/home/work
